# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/wizard" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "hamidraza"
      - "bharath-123"
      - "batphonghan"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/configuration" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "hamidraza"
      - "bharath-123"
      - "batphonghan"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/ui" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "hamidraza"
      - "bharath-123"
      - "batphonghan"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/demo" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "hamidraza"
      - "bharath-123"
      - "batphonghan"
