name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual release"
        required: false
        default: ""

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Create tag
        id: create_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          NEW_TAG=$(echo "$LATEST_TAG" | awk -F. '{ printf "v%d.%d.%d", $1, $2, $3+1 }')
          echo "New tag: $NEW_TAG"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "::set-output name=tag::${NEW_TAG}"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          name: Release ${{ steps.create_tag.outputs.tag }}
          draft: false
          prerelease: true

      - name: Build project
        working-directory: demo
        run: make build VERSION=${{ steps.create_tag.outputs.tag }}

      - name: Upload binaries to release
        if: ${{ success() }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: demo/bin/*
          tag: ${{ steps.create_tag.outputs.tag }}
          overwrite: true
          file_glob: true
